import React from 'react'

const form = [
    '個人制作','チーム制作'
];
// const position = [
//     'design','engineer'
// ];
const ArrayList1 = [
    { 
        name : "cosmocafe",
        catchCopy : "宇宙をモチーフにしたカフェのサイト",
        time : '40時間',
        day : '5ヶ月',
        tule : ['UIデザイン','企画','アニメーション','ロゴ作成'],
        // lang : lang.filter((t,i) => t == "html"|| t == "css"),
        lang : ['html','css'],
        form : form[0],
        about : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        img : "../image/cosmocafeLogo.png",
        hard : ['UIデザイン','コンセプト'],
        season :"1年生前期",
        // position : position,
        position : [0,1],
    },
    { 
        name : "freeme",
        catchCopy : "HackUでの作成",
        time : '10時間',
        day : '1ヶ月',
        tule : [],
        // lang : lang.filter((t,i) => t == "html"|| t == "css"),
        lang : ['html','css'],
        form : form[1],
        about : '1年生の夏休みの時期に制作したYahoo!Japan主催の学生ハッカソン"Hack U"にて制作したものです',
        img : "",
        hard : ['html','css'],
        season :"1年生前期",
        // position : position[1],
        position : [0],
    },
    { 
        name : "NONST",
        catchCopy : "もう溜め込まない",
        time : '24時間',
        day : '2週間',
        tule : [],
        // lang : lang.filter((t,i) => t == "html" || t == "css" || t == "javascript"),
        lang : ['html','css'],
        form : form[1],
        about : '1年生の夏休み時期に制作した学内短期制作にて制作したものです、愚痴を聞く人と話す人のマッチングアプリサービスです。',
        img : "",
        hard : ['html','css'],
        season :"1年生前期",
        // position : position[1],
        position : [0],
    },
    { 
        name : "GolePort",
        catchCopy : "非日常をあなたに",
        time : '40時間',
        day : '5ヶ月',
        tule : ['XD'],
        // lang : lang.filter((t,i) => t == "html" || t == "css"),
        lang : ['html','css'],
        form : '個人',
        about : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        img : "",
        hard : ['UIデザイン','コンセプト'],
        season :"1年生後期",
        // position : position,
        position : [0,1],
    },
    { 
        name : "うみとこころとぼく",
        catchCopy : "非日常をあなたに",
        time : '40時間',
        day : '5ヶ月',
        tule : ['XD'],
        // lang : lang.filter((t,i) => t == "html" || t == "css" || t == "javascript"),
        lang : ['html','css'],
        form : '個人',
        about : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        img : "",
        hard : ['html','css'],
        season :"1年生後期",
        // position : position[1],
        position : [0],
    },
    { 
        name : "fagory",
        catchCopy : "非日常をあなたに",
        time : '40時間',
        day : '5ヶ月',
        tule : ['XD'],
        // lang : lang.filter((t,i) => t == "html" || t == "css" || t == "javascript"),
        lang : ['html','css','JavaScript'],
        form : '個人',
        about : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        img : "",
        hard : ['UIデザイン','コンセプト'],
        season :"2年生前期",
        // position : position,
        position : [0,1],
    },
    { 
        name : "まつりる",
        catchCopy : "非日常をあなたに",
        time : '40時間',
        day : '5ヶ月',
        tule : ['UIデザイン','企画','アニメーション','ロゴ作成'],
        lang : [],
        form : '個人',
        about : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        img : "",
        season :"2年生前期",
        hard : [],
        // position : position[0],
        position : [1],
    },
    { 
        name : "おさけたて",
        catchCopy : "非日常をあなたに",
        time : '40時間',
        day : '5ヶ月',
        tule : ['UIデザイン','企画','アニメーション','ロゴ作成'],
        lang : [],
        form : '個人',
        about : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        img : "",
        season :"2年生前期",
        hard : [],
        // position : position[0],
        position : [1],
    },
];

const SkillArrayList = [
    {
        'age':'19歳',
        'from':'出身',
        'like':['服','甘いもの'],
        'lang':['html5','pug','css','scss','Javascript','React','Next'],
        'turl':['VisualStudioCode','Figma','Illustrator','PremierPro','AfterEffects','Indesign','XD']
    }
]

// const ArrayContext = React.createContext(ArrayList1);
// const langContext = React.createContext(lang);

export {ArrayList1,SkillArrayList};